MERGE `{{params.destination_dataset_project_id}}.{{params.destination_dataset_name}}.accounts` dest
USING {{params.dataset_name_temp}}.{{params.source_table}} source
ON FALSE
WHEN NOT MATCHED AND DATE(block_timestamp) = '{{ds}}' THEN
INSERT (
    block_number,
    block_timestamp,
    block_hash,
    pubkey,
    tx_signature,
    executable,
    lamports,
    owner,
    rent_epoch,
    program,
    space,
    account_type,
    is_native,
    mint,
    state,
    token_amount,
    token_amount_decimals,
    program_data,
    authorized_voters,
    authorized_withdrawer,
    prior_voters,
    node_pubkey,
    commission,
    epoch_credits,
    votes,
    root_slot,
    last_timestamp,
    data
) VALUES (
    block_number,
    block_timestamp,
    block_hash,
    pubkey,
    tx_signature,
    executable,
    lamports,
    owner,
    rent_epoch,
    program,
    space,
    account_type,
    is_native,
    mint,
    state,
    token_amount,
    token_amount_decimals,
    program_data,
    authorized_voters,
    authorized_withdrawer,
    prior_voters,
    node_pubkey,
    commission,
    epoch_credits,
    votes,
    root_slot,
    last_timestamp,
    data
)
WHEN NOT MATCHED BY source AND DATE(block_timestamp) = '{{ds}}' THEN
DELETE
